Update asr proto for offline diarization
nvidia-riva/common pull request #6
Opened 2022-07-13 16:07 UTC by mohnishparmar

2022-07-18 10:26 UTC, mohnishparmar commented
@ryanleary @findkim please review these proto changes for diarization

2022-07-18 11:48 UTC, mohnishparmar commented on riva/proto/riva_asr.proto
> +  // number of speakers. If not set, the default value is 6.
It not the default value but the parameter index, the default value should be handled in the code.

2022-09-02 21:24 UTC, messiaen requested changes

2022-09-02 21:24 UTC, messiaen commented on riva/proto/riva_asr.proto
> +  // Output only. A distinct integer value is assigned for every speaker within
Is it worth mentioning that `0` means no speaker tag?

2022-09-02 21:24 UTC, messiaen commented on riva/proto/riva_asr.proto
> +  int32 max_speaker_count = 3;
What do `max_speaker_count` and `min_speaker_count` map to in the nemo code? `max_speaker_count` is clear.  What does `min_speaker_count` do?

2022-10-07 18:12 UTC, closed without merging